"""add cart column to User

Revision ID: 1f14d05f4d06
Revises: 8b44e7e5c74d
Create Date: 2025-06-05 13:13:34.035512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f14d05f4d06'
down_revision = '8b44e7e5c74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cart')

    # ### end Alembic commands ###
